name: Postman API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install Newman
      run: npm install -g newman
    
    - name: Build API
      run: dotnet build ./server/server.csproj
    
    - name: Start API Server
      run: |
        dotnet run --project ./server/server.csproj &
        sleep 10
      
    - name: Run Postman Tests
      run: |
        newman run "./server/APi Övningar.postman_collection.json" -e "./server/New Environment.postman_environment.json"
